/**
 * Builds prompts/_index.yml from all individual prompt YAMLs.
 * This is the single source of truth that build-readme.ts consumes.
 *
 * Run: pnpm build:index
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import { loadAllPrompts } from './lib/load-prompts.ts';

const REPO_ROOT = resolve(import.meta.dirname, '..');

async function main() {
  const prompts = await loadAllPrompts(REPO_ROOT);

  const categories: Record<string, number> = {};
  for (const p of prompts) {
    categories[p.category] = (categories[p.category] ?? 0) + 1;
  }

  const index = {
    generated_at: new Date().toISOString(),
    total: prompts.length,
    categories,
    prompts: prompts.map((p) => ({
      id: p.id,
      file: p._file,
      category: p.category,
      title: p.title,
      intent: p.intent,
      preview: p.preview,
      hot_score: p.hot_score,
    })),
  };

  const yamlOut =
    '# This file is AUTO-GENERATED by scripts/build-index.ts\n' +
    '# Do not edit manually — your changes will be overwritten\n' +
    '# To regenerate: pnpm build:index\n\n' +
    stringifyYaml(index, { lineWidth: 0 });

  const outPath = resolve(REPO_ROOT, 'prompts/_index.yml');
  writeFileSync(outPath, yamlOut);
  console.log(`✅ Wrote ${outPath} (${prompts.length} prompts, ${Object.keys(categories).length} categories)`);
}

main().catch((e) => {
  console.error('❌ build-index failed:', e);
  process.exit(1);
});
